name: PR Frontend Dev - Docker Build & Test

on:
  push:
    branches:
      - dev
    paths:
      - 'train-ticket-machine-frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment: Development
    url: https://d2jdg3blz5bzw4.cloudfront.net
    permissions: # Add permissions for OIDC
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f train-ticket-machine-frontend/Dockerfile.build -t train-ticket-machine-frontend:pr train-ticket-machine-frontend

      - name: Run tests in Docker container
        run: docker run --rm train-ticket-machine-frontend:pr npm run test

      - name: Run test coverage in Docker container
        run: docker run --rm train-ticket-machine-frontend:pr npm run coverage

      - name: Sync with S3
        uses: ./.github/actions/aws-s3-sync
        with:
          bucket-name: ${{ secrets.S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
