name: PR Frontend Dev - Docker Build & Test

on:
  push:
    branches:
      - dev
    paths:
      - 'train-ticket-machine-frontend/**'
      - '.github/workflows/push-frontend-dev.yml'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    environment:
      name: Development
      url: https://d3i19dhhon0a88.cloudfront.net
    permissions: # Add permissions for OIDC
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f train-ticket-machine-frontend/Dockerfile.build -t train-ticket-machine-frontend:pr train-ticket-machine-frontend

      - name: Run tests in Docker container
        run: docker run --rm train-ticket-machine-frontend:pr npm run test

      - name: Run test coverage in Docker container
        run: docker run --rm train-ticket-machine-frontend:pr npm run coverage

      - name: Create container to extract build output
        run: docker create --name extract train-ticket-machine-frontend:pr

      - name: Copy build output
        run: docker cp extract:/app/dist ./dist

      - name: Remove extraction container
        run: docker rm extract

      - name: Sync with S3
        uses: ./.github/actions/aws-s3-sync
        with:
          bucket-name: ${{ secrets.S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
